### ISSUE TITLE
love for mint-client

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/mint-client#65]
- [ ] proper integration tests (#33)
- [ ] get off godeps (#63)
- [ ] fix `mintx unbond` (#62)
- [ ] version (#64)
